version: "3.9"

services:
  backend:
    build: .
    container_name: portfolio_teacher_backend
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
    command: npm start

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
